steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/deepseek-inference-api",
        "--build-arg",
        "HUGGINGFACE_TOKEN=$$_HUGGINGFACE_TOKEN",
        ".",
      ]
    secretEnv: ["_HUGGINGFACE_TOKEN"]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/deepseek-inference-api"]

images:
  - "gcr.io/$PROJECT_ID/deepseek-inference-api"

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/huggingface-token/versions/latest
      env: "_HUGGINGFACE_TOKEN"

options:
  machineType: "E2_HIGHCPU_8"
