steps:
  # Build step
  - name: "gcr.io/cloud-builders/docker"
    args: [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/deepseek-cloud-run-inference-api",
        "--build-arg",
        "HUGGINGFACE_TOKEN=$$_HUGGINGFACE_TOKEN",
        "-f",
        "Dockerfile", # Explicitly specify Dockerfile path
        ".", # Build context
      ]
    secretEnv: ["_HUGGINGFACE_TOKEN"]

  # Push step
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/deepseek-cloud-run-inference-api"]

  # Deploy step
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "deepseek-cloud-run-inference-api",
        "--image",
        "gcr.io/$PROJECT_ID/deepseek-cloud-run-inference-api",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--memory",
        "16Gi",
        "--cpu",
        "4",
        "--gpu",
      ]

# Secret configuration
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/huggingface-token/versions/latest
      env: "_HUGGINGFACE_TOKEN"

# Image outputs
images:
  - "gcr.io/$PROJECT_ID/deepseek-cloud-run-inference-api"

# Build options
options:
  machineType: "E2_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY
