steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg"
      - "HUGGINGFACE_TOKEN=${_HUGGINGFACE_TOKEN}"
      - "-t"
      - "${_IMAGE_NAME}"
      - "."
    secretEnv: ["_HUGGINGFACE_TOKEN"]

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/huggingface-token/versions/latest
      env: "_HUGGINGFACE_TOKEN"
