steps:
  # Build step
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/deepseek-inference-api",
        "-f",
        "Dockerfile",
        ".",
      ]

  # Push step
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/deepseek-inference-api"]

  # Deploy step
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "deepseek-service",
        "--image",
        "gcr.io/$PROJECT_ID/deepseek-inference-api",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--memory",
        "16Gi",
        "--cpu",
        "4",
        "--gpu",
      ]

# Image outputs
images:
  - "gcr.io/$PROJECT_ID/deepseek-inference-api"

# Build options
options:
  machineType: "E2_HIGHCPU_8"
  logging: "CLOUD_LOGGING_ONLY"
